language: node_js #运行环境
node_js: #指定版本
  -"10.16.0"
sudo: required #权限
before_install: sudo pip install foo
install: #安装依赖
   - ./install-dependencies.sh
   - ./install-aaaa.sh
script: py.test #运行
deploy: #部署
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
env: #定义环境变量
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"

